### ISSUE TITLE
change token

### ISSUE THREAD

**Issue by jmls** [kr1sp1n/node-vault#13]
I was wondering if you could change tokens after opening a vault session by setting the "token" property. Is this supported ?

**Comment by kr1sp1n** [comment]
Hi @jmls ,
should be possible because token is an instance variable defined in the constructor of the client:

https://github.com/kr1sp1n/node-vault/blob/master/src/node-vault.coffee#L14

So it should be possible to change it like this:

```javascript
var vault = require("node-vault")({token: 123});
// later ...
vault.token = 456;
```

Because with every request to the vault server the token will be read from here:

https://github.com/kr1sp1n/node-vault/blob/master/src/node-vault.coffee#L87

I hope that answers your question, does it?

**Comment by jmls** [comment]
works for me ;) thanks
