### ISSUE TITLE
policy example not clear

### ISSUE THREAD

**Issue by jmls** [kr1sp1n/node-vault#14]
Looking at the example to add a policy, it's not clear how to pass the rules
```
vault.addPolicy { name: 'mypolicy' }, (err, result)->
```
how are the rules meant to be passed in ? for example, should it be this ?

```
rules:[ {path: "sys/policy",  { policy: "write" } }] 
```

**Comment by kr1sp1n** [comment]
Hi @jmls ,
after reading https://github.com/hashicorp/vault/issues/582 I wrote a better example for you :smile: 
It seems that it is only possible to pass the rules as a String and not as an Object because the vault server parses the rules by itself. So since v0.4.4 the policies example should be much clearer.

**Comment by jmls** [comment]
thanks
